### ISSUE TITLE
implement method to return remapped indices of StencilArray

### ISSUE THREAD

**Issue by NilsNiggemann** [rafaqz/Stencils.jl#44]
I am thinking to make a PR to implement functionality to get the indices of a Stencil in the underlying array, but I am unsure about a few points (see below).
I stumbled with the following
```
A = StencilArray(zeros(4,4),Moore(),boundary = Wrap(),padding=Conditional())
4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

Moore{1, 2, 8, Nothing}
█▀█
▀▀▀

Wrap()
Conditional()

julia> neighbors(A,1,1) #correctly wraps
8-element StaticArraysCore.SVector{8, Float64} with indices SOneTo(8):
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

indices(stencil(A),1,1) #indices cannot be used to correctly index into A
8-element StaticArraysCore.SVector{8, Tuple{Int64, Int64}} with indices SOneTo(8):
 (0, 0)
 (1, 0)
 (2, 0)
 (0, 1)
 (2, 1)
 (0, 2)
 (1, 2)
 (2, 2)
```
I would like for a way for `indices` to return the indices that can be safely used to access the array elements. I suppose this could be changed by adding a new method:

`stencil_indices(A::AbstractStencilArray, I::CartesianIndex)` (or something like that), which returns indices and correctly handles boundary conditions

1. Is there already functionality that supports updating the values of a stencil that I overlooked?
2. Would such a PR be welcome? 
3. If yes: How should other arrays behave? 
* For Halos, do we allow to write to the halo or not?
* For the `Remove` boundary, I suppose we still have to throw an error if any of the indices are out of bounds. This is a little unfortunate but the padding is nowhere in memory so I don't see a good way to remap an index to it. 

Let me know what you think.

**Comment by rafaqz** [comment]
Ah right. Yes `indices` come from when Stencils was in DynamicGrids.jl and it was always a padded halo. It should really work as you say. But also making that consistent might be difficult. 

Do `indicies` indices still work for `getindex`/setindex!` for `Halo`? can we write into `0` ?

I'm not sure what to do for `Conditional`, maybe we should also check regular `getindex`/`setindex!` and just not write if the indices are in the halo? 

I would try not to throw an error for `Remove`, instead we can just silently do nothing on `setindex!` and return the pad value on `getindex`. Can that work? My reasoning is Stencils algs normally act on all the stencils in the array, so errors on the edges effectively mean errors everywhere.

And I would rather keep a single `indices` method than add another one with slightly different behavior. But this package being so high performance means we need to be pretty careful with the change.

A PR would be amazing. I don't have a lot of time for working on this package (or even remembering exactly how it works) so help is very much appreciated.

(I have also thought about adding a function to write a stencil to the grid that handles all of this without touching `getindex`/`setindex!`, but havent had time. And it is nice to have the free indices you can use how you like.)

**Comment by NilsNiggemann** [comment]
> Do `indicies` still work for getindex/setindex! for Halo? can we write into 0 ?
`indices` currently only takes a `Stencil` object which afaik does not know anything about the array that will be indexed. It will also return indices that are out of bounds and cannot be accessed.

> I'm not sure what to do for Conditional, maybe we should also check regular getindex/setindex! and just not write if the indices are in the halo?
Sure, that would also be an option.

> I would try not to throw an error for Halo or Conditional Remove, instead we can return the same indices but just silently do nothing on Conditinal setindex! and write into the halo for Halo. We can return the pad/halo value on getindex. Can that work? 
I think that should be possible in principle. It would mean to change the bounds checks in the padded arrays to account for the padding and allow `A[0]` etc (which makes sense). Although I am not super sure how one is supposed to handle the Halo after several `setindex!` calls. If we write first into `A[0]` and afterwards into `A[length(A)+1]` , what is the true value of the array? The only way to avoid ambiguities is to keep the Halo and the array in sync after each modification, right?

Still, refactoring `indices` to only return valid indices should not truly break anything unless I am mistaken. The only times it actually returns different indices is if the indices before would have thrown an out of bounds error (or have undefined behaviour I guess). 

> And I would rather keep a single indices method than add another one with slightly different behavior. But this package being so high performance means we need to be pretty careful with the change.

In the package, `indices` is only used in the `unsafe_neighbors` function (which makes a bounds check of the corners and calls the safe `getneighbor` function, if the stencil has overlap with the boundary.
Simply changing `indices` will have a performance penalty here, since for big arrays we do not actually need to remap the indices most of the time. I think it would be sensible to rename the old method to `unsafe_indices` to avoid paying this penalty.

If there are any other performance pitfalls, this might be a problem - At this point I am still not sure how this package manages to SIMD and probably cannot judge very well how performant the change will be. (BTW. isn't performance mostly dominated by memory accesses since the stencils are not contiguous in memory, or is there any clever way to circumvent this?)

< (I have also thought about adding a function to write a stencil to the grid that handles all of this without touching getindex/setindex!, but havent had time. And it is nice to have the free indices you can use how you like.

Actually, when I started drafting, I first wanted to propose a `setneighbors!` method, in analogy to the existing `neighbors`. This would definitely make a lot of sense as well. If you'd prefer, I could make a PR to implement this instead of changing indices (or we could do both).

I think I can make a PR as long as it is not too performance critical (I am not sure I have the capacity to dive into the KernelAbstractions stuff). I think both possibilities would be fine for performance though, this PR should not really affect anything that is already working and only introduce new things (which, granted, might not be as fast).

**Comment by rafaqz** [comment]
I'm happy to split out `unsafe_indices` and `indices`. But `indices` still needs to be pretty fast.

`setneighbors!` is what I was thinking too, that would be great to have. PR one or both, whatever you have energy for. But in separate PRs would be good.


Performance here is dominated by how much the compiler can freely optimise memory access and SIMD on its own. Everything is an SVector because this forces unrolling of `map` and loops (along with other StaticArrays.jl optimisations) and that gives the compiler free reign to reorganise and optimize. Its worth it because we compile once, run a million times. 
Stencils.jl is like ~40x faster than `mapwindow` in ImageFiltering.jl, and besides threading that\s because they use a `view` and run-time indices/run time loop lenghts, and here that's all known at compile time. That actually matters a lot more than just the raw cost of indexing from arrays. 

(For the extreme case, if we can fix KernelAbstractions.jl to iterate over CartesianIndices from the ground up we can actually get the compiler to see across multiple stencils and optimize most of the reads and operations away, because e.g. `sum` over neighboring stencils is doing the same read + op multiple times.  Its another order of magnitude improvement for functions like summing a bool window. We could also do it here without KA changes, by mapping over blocks of 8 and managing the indices within them ourselves.)

**Comment by NilsNiggemann** [comment]
> `setneighbors! is what I was thinking too, that would be great to have. PR one or both, whatever you have energy for. But in separate PRs would be good.`
Ok then,  I'll have a look at `setneighbors!` first. I think the best way to continue is for me to draft a PR, maybe then the questions regarding conventions for indexing into Halos etc will be more clear. I'll try to avoid throwing errors whenever possible for now.

> (For the extreme case, if we can fix KernelAbstractions.jl to iterate over statically known CartesianIndices from the ground up we can actually get the compiler to see across multiple stencils and optimize most of the reads and operations away, because e.g. sum over neighboring stencils is doing the same read + op multiple times. Its another order of magnitude improvement for functions like summing a bool window. We could also do it here without KA changes, by mapping over blocks of 8 and managing the indices within them ourselves.)

FWIW, I was amazed to see how efficient Stencils.jl already is. Since my current use case is restricted to comparably small arrays (< `100x100`, I thought inlining everything would bring a considerable improvement. I checked this with a 30x30 array for which I compared looping over stencils to a fully inlined function. There was barely any performance gain, and it the little gain that was there also went down with the matrix size. Still it would be cool to have a metaprogramming solution for indexing over all stencils.

**Comment by rafaqz** [comment]
Ok, I look forward to the PR.

You will notice that you really can't see any code "doing something" that should make Stencils.jl fast. There is some in StaticArrays.jl of course, but the main strategy here is putting as much as possible in the type and letting the compiler work it out. That seems to match or outperform any explicit optimisation schemes I can think up.

> Still it would be cool to have a metaprogramming solution for indexing over all stencils.

Can you expand on this a little?

**Comment by NilsNiggemann** [comment]
> Can you expand on this a little?

Oh I thought this was what you were referring to. Since the positions of indices are scattered everywhere in the array, many reading operations will be on the same array. This can be avoided in principle by writing a function like 
```
function getAllMooreStencils(A)
    P1 = SA[A[2], A[3], A[4], A[22], A[24], A[42], A[43], A[44]]
    [...]
    P162 = SA[A[357], A[358], A[359], A[377], A[379], A[397], A[398], A[399]]
    # do something with P1...P162
end
```
The compiler should hopefully be able to replace all superfluous calls to `getindex` (Or one could also make this explicit in the function). 
If this is actually faster, then one could try to achieve this with a generated function or something. (Although thats probably out of my league). In my test, I just checked how much I am leaving on the table by finding the indices at runtime.

**Comment by rafaqz** [comment]
Ahh right. The repeated reads arent as bad as you think as CPU caches mostly handle that well already. 

The gain I was refering to is the compiler also seeing that all the `+` ops in `sum` are acting on the same values and turning a `sum` mapwindow into a running sum for all windows, and other similar operations. That actually just happens already if you cut out KernelAbstractions.jl and loop over CartesianIndices manually - I think because the array size/CartiesianIndices are fixed at compile time and `sum` reductions are unrolled in StaticArrays.jl.

**Comment by rafaqz** [comment]
Yeah. If you loop over the `indices` of the stencil StaticArrays.jl will most likely make that fast without any other work.
