### ISSUE TITLE
Strange behaviour with SwitchingStencilArray

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/Stencils.jl#45]
When using a SwitchedStencilArray with either a Raster or a regular Array, under `mapstencil!`, I get extremely strange output. `mapstencil` seems to be fine.

Example:

```julia
using Rasters, Stencils, TestImages
using CairoMakie

lena = testimage("lena") .|> CairoMakie.Colors.Gray .|> Float64

heatmap(lena)

nabla = Stencils.Kernel(Stencils.Cross(1, 2), [0.5, 0.5, 0, 0.5, 0.5])

sa = StencilArray(lena, nabla)
mapstencil(kernelproduct, sa) |> heatmap # this is OK

ra = Raster(lena; dims = (X(1:size(lena, 1)), Y(1:size(lena, 2))))

mapstencil(kernelproduct, StencilArray(ra, nabla)) |> heatmap # this is OK
mapstencil(kernelproduct, SwitchingStencilArray(ra, nabla)) |> heatmap # this is OK
mapstencil!(kernelproduct, SwitchingStencilArray(ra, nabla)) |> x -> heatmap(x.source) # BAD BAD BAD
mapstencil!(kernelproduct, SwitchingStencilArray(lena, nabla)) |> x -> heatmap(x.source) # BAD BAD BAD

```
![download-15](https://github.com/rafaqz/Stencils.jl/assets/32143268/ead9a0be-9ee6-4331-970a-11e7a35f3587)

**Comment by rafaqz** [comment]
Does it need .source?

**Comment by asinghvi17** [comment]
Source and dest are the same here...so it may actually be a broken constructor or something.  Will have a look...

**Comment by asinghvi17** [comment]
As far as I can tell, this looks correct now.  Potentially a consequence of the DiskArrays PR I made for `collect_similar`.

**Comment by rafaqz** [comment]
There are other major problems with SwitchingStencilArray, I'm fixing it currently

**Comment by rafaqz** [comment]
I only use it as an abstract type through DynamicGrids and the one here is not well tested
