### ISSUE TITLE
Difference to ParallelStencil.jl

### ISSUE THREAD

**Issue by felixcremer** [rafaqz/Stencils.jl#9]
From a shallow reading of the READMEs and the name of the packages it seems, that this package is similar to https://github.com/omlins/ParallelStencil.jl. 
Did you have a look at ParallelStencil.jl?

**Comment by rafaqz** [comment]
Yeah, its actually quite different in practise.

This package gives you a collection of stencil shapes you can broadcast with a function of the neighborhood. Parallel or on single GPU.

ParallelStencil.jl uses macros over user defined functions to do a similar thing. I dont find it easily composable, and wasnt somethong I could easily plug in to DynamicGrids.jl.

We could use ParalelStencil.jl as a backend to run Stencils.jl over multiple GPUs, but my models are never that big so I havent bothered.

Anyway, I wrote all this before ParallelStencils.jl existed (this is neighbothood part of DynamicGrids.jl) and intended to call it Neighborhoods.jl, but the name is taken.
